name: Deploy on EXCloud

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to EXCloud
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 210.79.129.179
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            cd /home/ubuntu/learning_devops
            git pull
            npm install
            pm2 restart 0
